openapi: 3.0.0
paths:
  /api:
    get:
      operationId: AppController_get
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - App
  /api/todo:
    get:
      operationId: TodoController_getTodo
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetTodoDto'
      tags: &ref_0
        - Todo
    post:
      operationId: TodoController_postTodo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTodoDto'
      tags: *ref_0
    put:
      operationId: TodoController_putTodo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTodoDto'
      tags: *ref_0
    delete:
      operationId: TodoController_deleteTodo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTodoDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTodoDto'
      tags: *ref_0
info:
  title: Example
  description: The cats API description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    GetTodoDto:
      type: object
      properties:
        id:
          type: string
        complete:
          type: boolean
        title:
          type: string
        comment:
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - complete
        - title
        - comment
        - createdAt
        - updatedAt
    CreateTodoDto:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        comment:
          type: string
          minLength: 1
      required:
        - title
        - comment
    UpdateTodoDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
          minLength: 1
        comment:
          type: string
          minLength: 1
        complete:
          type: boolean
      required:
        - id
        - title
        - comment
        - complete
    DeleteTodoDto:
      type: object
      properties:
        id:
          type: string
      required:
        - id
